### PR TITLE
fix(VIA): matplotlib>=3.9 get_cmap compatibility

### PR DESCRIPTION
**Pull request by Starlitnightly**
## Problem
matplotlib 3.9 **removed** `matplotlib.cm.get_cmap` / `matplotlib.get_cmap` (use `matplotlib.colormaps[...]` or `pyplot.get_cmap`). The vendored VIA code still calls `cm.get_cmap(...)` / `matplotlib.cm.get_cmap(...)` in **20 places** across 4 files, so on CI runners with matplotlib>=3.9 `ov.single` VIA paths raise:

```
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

This currently fails `tests/single/test_stavia.py` (`get_gene_expression` tests) on the 3.11/3.12 builds — blocking unrelated PRs' CI.

## Fix
Replace all `cm.get_cmap(...)` / `matplotlib.cm.get_cmap(...)` with `plt.get_cmap(...)`, the documented cross-version replacement (works on matplotlib 3.8 and 3.9+, supports both the `(name)` and `(name, N)` forms). `plt` is already imported in all four files. Mechanical, behavior-preserving.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Starlitnightly** [comment]
Folding this matplotlib>=3.9 get_cmap fix directly into #836 instead, so #836's CI goes green on its own (avoids a dependent-PR train). Same change, same commit.
